### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by fake666** [ManClone/ledatroniclt3#1]
we should set this component up so it will work with HACS :)

**Comment by zillawilli** [comment]
Hello
I have a short questiion.
Is the project still ongoing or is it coming to an end
friendly greetings
willi

**Comment by fake666** [comment]
> Hello I have a short questiion. Is the project still ongoing or is it coming to an end friendly greetings willi

hi willi, i'm not currently developing this further, i'm a happy user as it is. do you need HACS support, or do you mean this repository in general? in case of the latter, it would probably be more helpful if you open a new issue, describing what you hope to achieve.

**Comment by zillawilli** [comment]
I have the problem that I cannot redirect the LEDATRONIC to my router.
This has been tried on IOS and Android. The app always displays the message: incorrect access data.

**Comment by fake666** [comment]
this is not the ledatronic support forum. please contact LEDA if you have issues with your system.

**Comment by fake666** [comment]
implemented HACS support in https://github.com/fake666/ledatroniclt3
