### ISSUE TITLE
ledatronic_temp over 255 it will beginn from 0 

### ISSUE THREAD

**Issue by tiran1984** [ManClone/ledatroniclt3#2]
when the temp will get higer then 255 it will start from 0

**Comment by tiran1984** [comment]
<img width="434" alt="grafik" src="https://user-images.githubusercontent.com/10049016/225432927-9397b347-9d4b-4098-9e46-7163e4126ebd.png">

**Comment by ManClone** [comment]
I have tested my changes and the temperature will now go up as much needed. Instead of adding 255 i mulutplicate the counter and i tested it up to over 800°C
